# In .travis.yml
gemfile:
  - gemfiles/3.0.20.gemfile
  - gemfiles/3.1.12.gemfile
  - gemfiles/3.2.19.gemfile
  - gemfiles/4.0.10.gemfile
  - gemfiles/4.1.6.gemfile

language: ruby
rvm:
  - "2.1.3"

install:
  - "bundle install"
  - "bundle exec appraisal install"

before_script:
  - "bundle exec rake db:migrate"

script:
  - "bundle exec rspec"