# In .travis.yml
gemfile:
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_5.0.0.gemfile
  - gemfiles/rails_5.1.0.gemfile
  - gemfiles/rails_5.2.0.gemfile

language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rspec
